title = "The Wine Cellar Music"
#baseURL = "https://github.com/EugenioRss/thewinecellarmusic.github.io/"
languageCode = "en-us"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
resourceDir = "./resources"
summaryLength = 10
disqusShortname = "https-main-thewinecellarmusic-netlify-app"

DefaultContentLanguage = "ita"
#SectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true


#weight = 1
contentDir = "content/blog"
# languageDirection = 'rtl' for Right-To-Left languages
    

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "Eugenio Rossini"
  favicon = "images/icon.png"
  site_logo = "images/icon.png"
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-purple"
  recent_posts_number = 3
  commentoEnable = false




[[params.ananke_socials]]
name = "github"
url = "https://github.com/EugenioRss"

[[params.ananke_socials]]
name = "instagram"
url = "https://www.instagram.com/the_wine_cellar_music/"



[menu]
[[menu.main]]
  name = 'Music'
  post = "<span class='alert'>New!</span>"
  pre = "<i class='fa fa-road'></i>"
  url = '/music/'
  weight = -100

[[menu.main]]
  identifier = 'Wine'
  name = 'Wine'
  pre = "<i class='fa fa-heart'></i>"
  url = '/wine/'
  weight = -50

[[menu.main]]
  identifier = 'About'
  name = 'About'
  pre = "<i class='fa fa-heart'></i>"
  url = '/about/'
  weight = 50

[[menu.main]]
  identifier = 'Contact'
  name = 'Contact'
  pre = "<i class='fa fa-heart'></i>"
  url = '/contact/'
  weight = 100

